routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::post('users/{user}/reset-password', 'UserController@reset')->name('users.reset');

    Route::resource('mainEquipments', 'MainEquipmentController');

    Route::resource('equipment', 'EquipmentController');

    Route::resource('teams', 'TeamController');
    Route::get('/getTeamName', 'TeamController@getTeamName');

    Route::resource('reports', 'ReportController');
    Route::get('/autoMainEquipData', 'ReportController@autoMainEquipData');

    Route::resource('jobs', 'JobController');
    Route::post('jobs/createTeam', 'JobController@createTeam')->name('jobs.createTeam');
    Route::post('jobs/updateTeam', 'JobController@updateTeam')->name('jobs.updateTeam');

    Route::get('/autoEquipData', 'ReportController@autoEquipData');

    Route::resource('jobTeams', 'JobTeamController');

    Route::get('histories', 'HistoryController@index')->name('histories.index');
    Route::post('histories/print', 'HistoryController@print')->name('histories.print');
});

app/Models/MainEquipment.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MainEquipment
 * @package App\Models
 * @version March 1, 2019, 7:58 am UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection Equipment
 * @property \Illuminate\Database\Eloquent\Collection jobTeams
 * @property \Illuminate\Database\Eloquent\Collection jobs
 * @property \Illuminate\Database\Eloquent\Collection Report
 * @property string name
 */
class MainEquipment extends Model
{
    public $table = 'main_equipments';
    public $timestamps = false;

    public $fillable = [
        'id',
        'name'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'name' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id' => 'unique:main_equipments',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function equipment()
    {
        return $this->hasMany(\App\Models\Equipment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function reports()
    {
        return $this->hasMany(\App\Models\Report::class);
    }
}

app/Http/Controllers/MainEquipmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMainEquipmentRequest;
use App\Http\Requests\UpdateMainEquipmentRequest;
use App\Models\Equipment;
use App\Models\MainEquipment;
use App\Models\Report;
use App\Repositories\MainEquipmentRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class MainEquipmentController extends AppBaseController
{
    /** @var  MainEquipmentRepository */
    private $mainEquipmentRepository;

    public function __construct(MainEquipmentRepository $mainEquipmentRepo)
    {
        $this->mainEquipmentRepository = $mainEquipmentRepo;
    }

    /**
     * Display a listing of the MainEquipment.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->mainEquipmentRepository->pushCriteria(new RequestCriteria($request));
        $mainEquipments = $this->mainEquipmentRepository->orderBy('id', 'asc')->all();

        $main_equipment_option = MainEquipment::all()->pluck('name', 'id');
        $main_equipment_option->prepend('Please Select');

        return view('main_equipments.index', compact('mainEquipments','main_equipment_option'));
    }

    /**
     * Show the form for creating a new MainEquipment.
     *
     * @return Response
     */
    public function create()
    {
        return view('main_equipments.create');
    }

    /**
     * Store a newly created MainEquipment in storage.
     *
     * @param CreateMainEquipmentRequest $request
     *
     * @return Response
     */
    public function store(CreateMainEquipmentRequest $request)
    {
        $input = $request->all();

        $mainEquipment = $this->mainEquipmentRepository->create($input);

        Flash::success('Main Equipment saved successfully.');

        return redirect(route('mainEquipments.index'));
    }

    /**
     * Display the specified MainEquipment.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $mainEquipment = $this->mainEquipmentRepository->findWithoutFail($id);

        if (empty($mainEquipment)) {
            Flash::error('Main Equipment not found');

            return redirect(route('mainEquipments.index'));
        }

        $equipments = Equipment::where('main_equipment_id', $id)->orderBy('id', 'asc')->get();
        $mainEquipmentName = MainEquipment::where('id', $id)->first(['name']);

        return view('main_equipments.show', compact('equipments', 'mainEquipmentName'));
    }

    /**
     * Show the form for editing the specified MainEquipment.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $mainEquipment = $this->mainEquipmentRepository->findWithoutFail($id);

        if (empty($mainEquipment)) {
            Flash::error('Main Equipment not found');

            return redirect(route('mainEquipments.index'));
        }

        return view('main_equipments.edit')->with('mainEquipment', $mainEquipment);
    }

    /**
     * Update the specified MainEquipment in storage.
     *
     * @param  int              $id
     * @param UpdateMainEquipmentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMainEquipmentRequest $request)
    {
        $mainEquipment = $this->mainEquipmentRepository->findWithoutFail($id);

        if (empty($mainEquipment)) {
            Flash::error('Main Equipment not found');

            return redirect(route('mainEquipments.index'));
        }

        $mainEquipment = $this->mainEquipmentRepository->update($request->all(), $id);

        Flash::success('Main Equipment updated successfully.');

        return redirect(route('mainEquipments.index'));
    }

    /**
     * Remove the specified MainEquipment from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $mainEquipment = $this->mainEquipmentRepository->findWithoutFail($id);

        if (empty($mainEquipment)) {
            Flash::error('Main Equipment not found');

            return redirect(route('mainEquipments.index'));
        }

        $reports = Report::where('main_equipment_id', $id)->count();

        if ($reports > 0) {
            Flash::error('Masih ada data report yang menggunakan Main Equipment ini');

            return redirect(route('mainEquipments.index'));
        }

        $equipments = Equipment::where('main_equipment_id', $id)->count();

        if ($equipments > 0) {
            Flash::error('Masih ada data equipment yang menggunakan Main Equipment ini');

            return redirect(route('mainEquipments.index'));
        }

        $this->mainEquipmentRepository->delete($id);

        Flash::success('Main Equipment deleted successfully.');

        return redirect(route('mainEquipments.index'));
    }
}

resources/views/main_equipments/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Main Equipment
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'mainEquipments.store']) !!}

                        @include('main_equipments.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/main_equipments/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Main Equipment
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($mainEquipment, ['route' => ['mainEquipments.update', $mainEquipment->id], 'method' => 'patch']) !!}

                        @include('main_equipments.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/main_equipments/fields.blade.php
<div class="form-group col-sm-6">
    {!! Form::label('id', 'Code:') !!}
    {!! Form::text('id', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('mainEquipments.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/main_equipments/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Main Equipments</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('mainEquipments.create') !!}">Add New Main Equipment</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('main_equipments.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/main_equipments/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Equipment of {!! $mainEquipmentName->name !!}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('main_equipments.show_fields')
                    <a href="{!! route('mainEquipments.index') !!}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/main_equipments/show_fields.blade.php
<table class="table table-responsive" id="equipment-table">
    <thead>
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th colspan="3">Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach($equipments as $equipment)
        <tr>
            <td>{!! $equipment->id !!}</td>
            <td>{!! $equipment->name !!}</td>
            <td>
                {!! Form::open(['route' => ['equipment.destroy', $equipment->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('equipment.edit', [$equipment->id]) !!}" class='btn btn-default btn-xs'>Edit</a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/main_equipments/table.blade.php
<table class="table table-responsive" id="mainEquipments-table">
    <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th colspan="4">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($mainEquipments as $mainEquipment)
        <tr>
            <td>{!! $mainEquipment->id !!}</td>
            <td>{!! $mainEquipment->name !!}</td>
            <td>
                {!! Form::open(['route' => ['mainEquipments.destroy', $mainEquipment->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    {!! Form::button('Tambah Equipment', ['type' => 'button', 'class' => 'btn btn-info btn-xs', 'data-toggle' => "modal", 'data-target' => "#equipModal-$mainEquipment->id"]) !!}
                    <a href="{!! route('mainEquipments.show', [$mainEquipment->id]) !!}" class='btn btn-default btn-xs'>Lihat Equipment</a>
                    <a href="{!! route('mainEquipments.edit', [$mainEquipment->id]) !!}" class='btn btn-default btn-xs'>Edit</a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>

        <!-- Modal -->
        <div id="equipModal-{!! $mainEquipment->id !!}" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add New Equipment</h4>
                    </div>
                    <div class="modal-body">
                        {!! Form::open(['route' => 'equipment.store']) !!}

                        @include('equipment.fields')

                        {!! Form::close() !!}
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>

            </div>
        </div>
    @endforeach
    </tbody>
</table>