routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::post('users/{user}/reset-password', 'UserController@reset')->name('users.reset');

    Route::resource('mainEquipments', 'MainEquipmentController');

    Route::resource('equipment', 'EquipmentController');

    Route::resource('teams', 'TeamController');
    Route::get('/getTeamName', 'TeamController@getTeamName');

    Route::resource('reports', 'ReportController');
    Route::get('/autoMainEquipData', 'ReportController@autoMainEquipData');

    Route::resource('jobs', 'JobController');
    Route::post('jobs/createTeam', 'JobController@createTeam')->name('jobs.createTeam');
    Route::post('jobs/updateTeam', 'JobController@updateTeam')->name('jobs.updateTeam');

    Route::get('/autoEquipData', 'ReportController@autoEquipData');

    Route::resource('jobTeams', 'JobTeamController');

    Route::get('histories', 'HistoryController@index')->name('histories.index');
    Route::post('histories/print', 'HistoryController@print')->name('histories.print');
});

app/Models/JobTeam.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class JobTeam
 * @package App\Models
 * @version April 1, 2019, 2:35 pm +07
 *
 * @property \App\Models\Job job
 * @property \App\Models\Team team
 * @property \Illuminate\Database\Eloquent\Collection jobs
 * @property integer team_id
 */
class JobTeam extends Model
{
    public $table = 'job_teams';
    public $timestamps = false;

    public $fillable = [
        'team_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'job_id' => 'integer',
        'team_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function job()
    {
        return $this->belongsTo(\App\Models\Job::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function team()
    {
        return $this->belongsTo(\App\Models\Team::class);
    }
}

app/Http/Controllers/JobTeamController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateJobTeamRequest;
use App\Http\Requests\UpdateJobTeamRequest;
use App\Repositories\JobTeamRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class JobTeamController extends AppBaseController
{
    /** @var  JobTeamRepository */
    private $jobTeamRepository;

    public function __construct(JobTeamRepository $jobTeamRepo)
    {
        $this->jobTeamRepository = $jobTeamRepo;
    }

    /**
     * Display a listing of the JobTeam.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Show the form for creating a new JobTeam.
     *
     * @return Response
     */
    public function create()
    {
        return redirect(route('reports.index'));
    }

    /**
     * Store a newly created JobTeam in storage.
     *
     * @param CreateJobTeamRequest $request
     *
     * @return Response
     */
    public function store(CreateJobTeamRequest $request)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Display the specified JobTeam.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Show the form for editing the specified JobTeam.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Update the specified JobTeam in storage.
     *
     * @param  int              $id
     * @param UpdateJobTeamRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateJobTeamRequest $request)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Remove the specified JobTeam from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        return redirect(route('reports.index'));
    }
}

resources/views/job_teams/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job Team
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'jobTeams.store']) !!}

                        @include('job_teams.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/job_teams/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job Team
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($jobTeam, ['route' => ['jobTeams.update', $jobTeam->id], 'method' => 'patch']) !!}

                        @include('job_teams.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/job_teams/fields.blade.php
<!-- Team Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('team_id', 'Team Id:') !!}
    {!! Form::number('team_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('jobTeams.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/job_teams/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Job Teams</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('jobTeams.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('job_teams.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/job_teams/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Job Team
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('job_teams.show_fields')
                    <a href="{!! route('jobTeams.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/job_teams/show_fields.blade.php
<!-- Job Id Field -->
<div class="form-group">
    {!! Form::label('job_id', 'Job Id:') !!}
    <p>{!! $jobTeam->job_id !!}</p>
</div>

<!-- Team Id Field -->
<div class="form-group">
    {!! Form::label('team_id', 'Team Id:') !!}
    <p>{!! $jobTeam->team_id !!}</p>
</div>

resources/views/job_teams/table.blade.php
<table class="table table-responsive" id="jobTeams-table">
    <thead>
        <tr>
            <th>Team Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($jobTeams as $jobTeam)
        <tr>
            <td>{!! $jobTeam->team_id !!}</td>
            <td>
                {!! Form::open(['route' => ['jobTeams.destroy', $jobTeam->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('jobTeams.show', [$jobTeam->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('jobTeams.edit', [$jobTeam->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>