routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::post('users/{user}/reset-password', 'UserController@reset')->name('users.reset');

    Route::resource('mainEquipments', 'MainEquipmentController');

    Route::resource('equipment', 'EquipmentController');

    Route::resource('teams', 'TeamController');
    Route::get('/getTeamName', 'TeamController@getTeamName');

    Route::resource('reports', 'ReportController');
    Route::get('/autoMainEquipData', 'ReportController@autoMainEquipData');

    Route::resource('jobs', 'JobController');
    Route::post('jobs/createTeam', 'JobController@createTeam')->name('jobs.createTeam');
    Route::post('jobs/updateTeam', 'JobController@updateTeam')->name('jobs.updateTeam');

    Route::get('/autoEquipData', 'ReportController@autoEquipData');

    Route::resource('jobTeams', 'JobTeamController');

    Route::get('histories', 'HistoryController@index')->name('histories.index');
    Route::post('histories/print', 'HistoryController@print')->name('histories.print');
});

app/Models/Report.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Report
 * @package App\Models
 * @version March 4, 2019, 2:16 am UTC
 *
 * @property \App\Models\MainEquipment mainEquipment
 * @property \Illuminate\Database\Eloquent\Collection jobTeams
 * @property \Illuminate\Database\Eloquent\Collection Job
 * @property string main_equipment_id
 */
class Report extends Model
{
    public $table = 'reports';

    public $fillable = [
        'main_equipment_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'main_equipment_id' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function mainEquipment()
    {
        return $this->belongsTo(\App\Models\MainEquipment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function jobs()
    {
        return $this->hasMany(\App\Models\Job::class);
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateReportRequest;
use App\Http\Requests\UpdateReportRequest;
use App\Models\Equipment;
use App\Models\Job;
use App\Models\MainEquipment;
use App\Models\Report;
use App\Repositories\ReportRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class ReportController extends AppBaseController
{
    /** @var  ReportRepository */
    private $reportRepository;

    public function __construct(ReportRepository $reportRepo)
    {
        $this->reportRepository = $reportRepo;
    }

    /**
     * Display a listing of the Report.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $to = date('Y-m-d H:i:s');
        $from = date('Y-m-d H:i:s', strtotime("-1 days"));
        $this->reportRepository->pushCriteria(new RequestCriteria($request));

        $reports = Report::whereBetween('created_at', [$from, $to])->get();

        return view('reports.index', compact('reports'));
    }

    /**
     * Show the form for creating a new Report.
     *
     * @return Response
     */
    public function create()
    {
        $mainEquipmentOption = MainEquipment::orderBy('id','asc')->get()->pluck('name', 'id', 'name');
        
        return view('reports.create', compact('mainEquipmentOption'));
    }

    /**
     * Store a newly created Report in storage.
     *
     * @param CreateReportRequest $request
     *
     * @return Response
     */
    public function store(CreateReportRequest $request)
    {
        $input = $request->all();

        $report = $this->reportRepository->create($input);

        Flash::success('Data saved successfully.');

        return redirect(route('reports.index'));
    }

    /**
     * Display the specified Report.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Show the form for editing the specified Report.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Update the specified Report in storage.
     *
     * @param  int              $id
     * @param UpdateReportRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateReportRequest $request)
    {
        return redirect(route('reports.index'));
    }

    /**
     * Remove the specified Report from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $report = $this->reportRepository->findWithoutFail($id);

        if (empty($report)) {
            Flash::error('Report not found');

            return redirect(route('reports.index'));
        }

        $jobs = Job::where('report_id', $id)->count();

        if ($jobs > 0) {
            Flash::error('Report ini masih memiliki data job');

            return redirect(route('reports.index'));
        }

        $this->reportRepository->delete($id);

        Flash::success('Report deleted successfully.');

        return redirect(route('reports.index'));
    }

    public function autoMainEquipData(Request $request)
    {
        $data = [];

        if ($request->has('q')) {
            $autoMainEquip = $request->q;
            $data = DB::table('main_equipments')->select('id', 'name')->where('id', 'LIKE', "%$autoMainEquip%")->get();
        }

        return response()->json($data);
    }

    public function autoEquipData(Request $request)
    {
        $data = [];

        if ($request->has('q')) {
            $autoMainEquip = $request->q;
            $mainEquipId = $request->mainEquipId;
            $data = DB::table('equipments')->select('id', 'name')->where('id', 'LIKE', "%$autoMainEquip%")
                ->where('main_equipment_id', '=', $mainEquipId)->get();
        }

        return response()->json($data);
    }


}

resources/views/reports/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Main Equipment
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'reports.store']) !!}

                        @include('reports.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/reports/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Report
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($report, ['route' => ['reports.update', $report->id], 'method' => 'patch']) !!}

                        @include('reports.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/reports/fields.blade.php
<!-- Main Equipment Id Field -->
<div class="container form-group col-sm-6">
    {!! Form::label('main_equipment_id', 'Main Equipment Id:') !!}
    <select class="main_equipment_id form-control" name="main_equipment_id"></select>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('reports.index') !!}" class="btn btn-default">Cancel</a>
</div>

<script type="text/javascript">
    $('.main_equipment_id').select2({
        placeholder: 'Type Main Equipment Code ...',
        ajax: {
            url: '{!! url('/autoMainEquipData') !!}',
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results:  $.map(data, function (item) {
                        return {
                            text: item.id+' - '+item.name,
                            id: item.id
                        }
                    })
                };
            },
            cache: true
        }
    });
</script>

resources/views/reports/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Daftar Lokasi Pekerjaan Hari ini</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('reports.create') !!}">Tambah Main Equipment</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('reports.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/reports/job_table.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Daftar Pekerjaan {!! $mainEquipName !!}</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('reports.index') !!}">Kembali ke Daftar Lokasi Pekerjaan</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                <table class="table table-responsive" id="jobs-table">
                    <thead>
                        <tr>
                            <th>Equipment</th>
                            <th>Work Order</th>
                            <th>Realisation</th>
                            <th>Team PGO</th>
                            <th>Status</th>
                            <th>User</th>
                            <th>PGOH</th>
                            <th>Start</th>
                            <th>Finish</th>
                            <th>Result</th>
                            <th colspan="3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($jobs as $job)
                        <tr>
                            <td>{!! $job->equipment_id !!}<br>({!! $job->equipment->name !!})</td>
                            <td>
                                @php
                                    $workArray = explode(',', $job->work_order);
                                @endphp
                                <ol>
                                    @foreach($workArray as $work)
                                        <li>{!! $work !!}</li>
                                    @endforeach
                                </ol>
                            </td>
                            <td>@if($job->realisation != "" || $job->realisation != null)
                                    @php
                                        $realArray = explode(',', $job->realisation);
                                    @endphp
                                    <ol>
                                        @foreach($realArray as $real)
                                            <li>{!! $real !!}</li>
                                        @endforeach
                                    </ol>
                                @else
                                    Belum Ada
                                @endif
                            </td>
                            <td>
                                @if($job->team === 'Belum Ada')
                                    {{$job->team}}
                                @else
                                    @foreach($job->team as $team)
                                        {{$team->team->name}} <br>
                                    @endforeach
                                @endif
                            </td>
                            <td>
                                @if($job->status == 'F')
                                    Failed
                                @elseif($job->status == 'C')
                                    Completed
                                @elseif($job->status == 'P')
                                    Pending
                                @else
                                    Belum Diset
                                @endif
                            </td>
                            <td>{!! $job->user_amount !!}</td>
                            <td>{!! $job->pgooh_amount !!}</td>
                            <td>{!! $job->start_time !!}</td>
                            <td>
                                @if($job->finish_time != null)
                                    {!! $job->finish_time !!}
                                @else
                                    00:00:00
                                @endif
                            </td>
                            <td>
                                @if($job->finish_time != null)
                                    @php
                                        $timeFinish = $job->finish_time;
                                        $timeStart = $job->start_time;
                                        $interval = intval((strtotime($timeFinish) - strtotime($timeStart))/60);

                                        $hours = intval($interval/60);
                                        $minutes = $interval%60;
                                    @endphp
                                    {!! $hours !!}:{!! $minutes !!}
                                @else
                                    00:00:00
                                @endif
                            </td>
                            <td>
                                {!! Form::open(['route' => ['jobs.destroy', $job->id], 'method' => 'delete']) !!}
                                <div class='btn-group'>
                                    @if($job->team === 'Belum Ada')
                                        <a id="teamBtn" href="" class="btn btn-info btn-xs" data-toggle="modal" data-target="#add-team-{!! $job->id !!}">Tambah Personel</a>
                                    @else
                                        <a id="teamBtnUpdate" href="" class="btn btn-success btn-xs" data-toggle="modal" data-target="#update-team-{!! $job->id !!}">Update Personel</a>
                                    @endif
                                    <a href="{!! route('jobs.edit', [$job->id]) !!}" class='btn btn-default btn-xs'>Realisasi</a>
                                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                </div>
                                {!! Form::close() !!}
                            </td>
                        </tr>

                        <div id="add-team-{!! $job->id !!}" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Add Personel</h4>
                                    </div>
                                    <div class="modal-body">
                                        {!! Form::open(['route' => 'jobs.createTeam']) !!}
                                            @include('reports.team_fields')
                                        {!! Form::close() !!}
                                    </div>
                                    <div class="modal-footer">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="update-team-{!! $job->id !!}" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Update Personel</h4>
                                        </div>
                                        <div class="modal-body">
                                            {!! Form::open(['route' => 'jobs.updateTeam']) !!}
                                                @include('reports.team_fields')
                                            {!! Form::close() !!}
                                        </div>
                                        <div class="modal-footer">
                                        </div>
                                    </div>
                                </div>
                            </div>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">
        </div>
    </div>
@endsection

resources/views/reports/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Report
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('reports.show_fields')
                    <a href="{!! route('reports.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/reports/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $report->id !!}</p>
</div>

<!-- Main Equipment Id Field -->
<div class="form-group">
    {!! Form::label('main_equipment_id', 'Main Equipment Id:') !!}
    <p>{!! $report->main_equipment_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $report->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $report->updated_at !!}</p>
</div>

resources/views/reports/table.blade.php
<table class="table table-responsive" id="reports-table">
    <thead>
        <tr>
            <th>Main Equipment</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Jobs</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($reports as $report)
        <tr>
            <td>{!! $report->main_equipment_id !!} - {!! $report->mainEquipment->name !!}</td>
            <td>{!! $report->created_at->format('l, F Y H:i:s') !!}</td>
            <td>{!! $report->updated_at->format('l, F Y H:i:s') !!}</td>
            <td>
                <div class='btn-group'>
                    <a href="{!! route('jobs.show', [$report->id]) !!}" class='btn btn-default btn-xs'>Lihat Daftar</a>
                    <a id="jobBtn" href="" class="btn btn-info btn-xs" data-toggle="modal" data-target="#add-job-{!! $report->id !!}">Tambah</a>
                </div>
            </td>
            <td>
                {!! Form::open(['route' => ['reports.destroy', $report->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>

        <div id="add-job-{!! $report->id !!}" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Tambah Pekerjaan untuk {!! $report->main_equipment_id !!} - {!! $report->mainEquipment->name !!}</h4>
                    </div>
                    <div class="modal-body">
                        {!! Form::open(['route' => 'jobs.store']) !!}
                            @include('jobs.fields')
                        {!! Form::close() !!}
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>

            </div>
        </div>
    @endforeach
    </tbody>
</table>

<script type="text/javascript">
    $('#jobBtn').on('click', function (e) {
        var mainEquipmentId = $('#main_equipment_id').val();

        $('.equipment_id').select2({
            placeholder: 'Type Equipment Code ...',
            ajax: {
                url: '{!! url('/autoEquipData') !!}',
                dataType: 'json',
                type:'GET',
                delay: 250,
                data: function (params) {
                    return {
                        q: params.term,
                        mainEquipId: mainEquipmentId
                    };
                },
                processResults: function (data) {
                    return {
                        results:  $.map(data, function (item) {
                            return {
                                text: item.id+' - '+item.name,
                                id: item.id
                            }
                        })
                    };
                },
                cache: true
            }
        });
    });
</script>

resources/views/reports/team_fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
        {!! Form::label('name', 'Name:') !!}
        <select style="width: 100%" class="team_name form-control" multiple="multiple" name="name[]"></select>
        <input type="hidden" name="job_id" value="{{$job->id}}"/>
        <input type="hidden" name="report_id" value="{{$reportID}}"/>
    </div>
    
    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        @if(isset($edit))
            <a href="{!! route('teams.index') !!}" class="btn btn-default">Cancel</a>
        @else
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        @endif
    </div>
    
    <script type="text/javascript">
        $('.team_name').select2({
            placeholder: 'Type Name ...',
            ajax: {
                url: '{!! url('/getTeamName') !!}',
                dataType: 'json',
                delay: 250,
                processResults: function (data) {
                    return {
                        results:  $.map(data, function (item) {
                            return {
                                text: item.name,
                                id: item.id
                            }
                        })
                    };
                },
                cache: true
            }
        });
    </script>